[package]
name = "kyefa"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
iced = "0.13.1"
serde = "1.0.219"
sqlx = "0.8.6"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
